// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AnimationState {
  time_position: number;
  description: string;
  state_data: string;
  is_key_state: boolean;
}
