// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DomainReference {
  domain: string;
  object_type: string;
  object_id: string;
  display_name: string;
  hover_description: string | null;
  latex: string | null;
}
