// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GroupDefinition {
  name: string;
  order: number | null;
  is_abelian: boolean;
  is_cyclic: boolean;
  is_finite: boolean;
  identity_symbol: string;
  operation_symbol: string;
}
