// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GroupHomomorphism {
  name: string;
  domain: string;
  codomain: string;
  is_isomorphism: boolean;
  is_monomorphism: boolean;
  is_epimorphism: boolean;
  is_endomorphism: boolean;
  is_automorphism: boolean;
}
