// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GroupElement {
  symbol: string;
  order: number | null;
  is_identity: boolean;
  is_involution: boolean;
  inverse_symbol: string | null;
}
