// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MathObjectMetadata {
  id: string;
  name: string;
  domain: string;
  object_type: string;
  description: string;
  discovery_date: string | null;
  discoverer: string | null;
  importance: number;
  difficulty: number;
  tags: Array<string>;
  latex: string | null;
}
