// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathObjectMetadata } from "./MathObjectMetadata";

export interface MathModule {
  metadata: MathObjectMetadata;
  submodules: Array<string> | null;
  definitions: Array<string> | null;
  theorems: Array<string> | null;
  examples: Array<string> | null;
  learning_objectives: Array<string> | null;
}
