// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationData } from "./AnimationData";
import type { DomainReference } from "./DomainReference";

export interface ProofStep {
  step_number: number;
  description: string;
  latex: string;
  justification: string;
  animation: AnimationData | null;
  references: Array<DomainReference> | null;
}
