// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainReference } from "./DomainReference";
import type { ProofStep } from "./ProofStep";

export interface Proof {
  method: string;
  steps: Array<ProofStep>;
  key_insights: Array<string>;
  alternative_approaches: Array<string> | null;
  references: Array<DomainReference>;
}
